from .ap_crossover import APCrossOver
from .cx_crossover import CXCrossOver
from .er_crossover import ERCrossOver
from .mpx_crossover import MPXCrossOver
from .ox1_crossover import OX1CrossOver
from .ox2_crossover import OX2CrossOver
from .pmx_crossover import PMXCrossOver
from .pos_crossover import POSCrossOver
from .vr_crossover import VRCrossOver
